name: june_intro_page_lego
description: "lego is all you need"
#publish_to: 'none'
repository: https://github.com/melodysdreamj/june_intro_page_lego

version: 1.0.0+2

environment:
  sdk: '>=3.3.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  june_flow_util: #@add
  styled_widget: #@add
  modal_bottom_sheet: #@add
  gap: #@add
  flutter_svg: #@add

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints:

flutter:
  assets:
    - assets/lego/june_intro_page_lego/
  uses-material-design: true

topics:
  - lego